In [31]:
import numpy as np

In [32]:
list1 = [1, 2, 3]
print('list1 type:', type(list1))
array1 = np.array(list1)
#array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape) # 튜플 형태로 들어있는걸알수있다.
# PANDAS에서도 shape확인했다.  인덱스 - 행,  index[1] 하면 - 열  나왔다.
# 1차원 배열의 길이 정보가 나옴.  
# 1차원배열은 행ㅇ ㅓㅂㅅ고  열만 있는 상태.  
# 근데  빈 , 는ㄴ 왜요?  튜플이 요소가 1개일때는 뒤에 comma 가 붙어요. 



list1 type: <class 'list'>
array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [33]:
array2 = np.array([[1,2,3],
                  [2,3,4]])
# 1차원 리스트가 2개가 있는데,  그걸 감싸는 list 가 있다. 
# 행 2개고 열3개  , 2행3열짜리 2차원 데이터프레임
# shape 출력했는데 튜플이 나오고 그 튜플이 요소 2개 가지면?
#무조건 2차원 배열이에요 
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [34]:
print('array1: {}차원, array2: {}차원, array3: {}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


### ndarray의 데이터 타입

In [45]:
list1 = [1,2,3,]# 여기 2.5 추가되면 전체가 float64 타입 화 된다.
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)
print(array1.shape)
array1 
#명령어로 출력하면  comma 잘 나옴

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32
(3,)


array([1, 2, 3])

In [36]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [46]:
# change type int to float 
# . 붙는 이유? , 안붙게 하려면?
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64') # array_int.astype(np.float64)
# 넘파이에서도 제공 되는 astype 이고 똑같이 써먹을수있다! 
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [47]:
array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [48]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype) 

[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [38]:
sequence_array = np.arange(10)

# range  /  orange / arrange /  arange??????????????


print(sequence_array)
print(type(sequence_array))
print(sequence_array.dtype, sequence_array.shape)

# 튜플 타입 (단개짜리) int32 (10,) 


[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int32 (10,)


In [49]:
## 모든 원소가 0인 ndarray 생성
## shape : (3, 2)
## dtype : int32
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)


[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [39]:
## 모든 원소가 1인 ndarray 생성
## shape : (3, 2)
## dtype : float64
one_array = np.ones((3, 2))
# 1따리 배열 만들기  ones 메서드
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape

In [52]:
#작업하게되면 셰이프 변경할일이 자주 생긴다. 
# 1차원배열 

array1 = np.arange(10)
print('array1:\n', array1)
print('shape ;::' ,  array1.shape)

array1:
 [0 1 2 3 4 5 6 7 8 9]
shape ;:: (10,)


In [61]:
## 1차원배열 10개짜리를  2차원배열로 HOW?? (2, 5) shape으로 변환
array1 = np.arange(10)
array2 = array1.reshape(2, 5)
print('array2:\n', array2)
#array2 = array1.reshape(5, 2)
#print('array2:\n', array2)

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [62]:
## 동일 한 2차원 배열이지만 /  행 / 열 을 뒤집기 
## (5, 2) shape으로 변환
print('array2:\n', array2)# 2,5  >>>> 5,2 
array3 = array2.reshape(5, 2)
print('array3:\n', array3)

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [41]:
array1.reshape(4, 3)#만들수 있는 형태의 셰이프를 지정을 좀 하자.

ValueError: cannot reshape array of size 10 into shape (4,3)

In [67]:
array1 = np.arange(10)
print(array1)
print('array1 shape:', array1.shape)
array2 = array1.reshape(-1, 5)
# 열이 일단 꼭 5개면 좋겠어요 .
# 근데 행이 얼만지 관심도 , 계산 하기도 귀찮아요.
print('array2 shape:', array2.shape)


array3 = array2.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array1 shape: (10,)
array2 shape: (2, 5)
array3 shape: (5, 2)


In [71]:
array1 = np.arange(10)
print(array1)
array4 = array1.reshape(-1, 4)

[0 1 2 3 4 5 6 7 8 9]


ValueError: cannot reshape array of size 10 into shape (4)

In [73]:
# 3차원단계

array1 = np.arange(8)

## 1차원 -> 3차원 변환
array3 = array1.reshape((2, 2, 2))
#  2 층짜리의 블럭이있어요.
print('array3:\n', array3.tolist())
print('array3:\n', array3)


array3:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array3:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [75]:

## 3차원 -> 2차원 변환, 컬럼 갯수 : 1
array44 = array3.reshape(-1, 1,1)
print('array44:\n', array44.tolist())
print('array44 shape:', array44.shape)
array4 = array3.reshape(-1, 1) # 행은 가변으로 하고,  열은 1개로 리셰이프좀요.
print('array4:\n', array4.tolist())
print('array4 shape:', array4.shape)

## 1차원 -> 2차원 변환, 컬럼 갯수 : 1
array5 = array1.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

array44:
 [[[0]], [[1]], [[2]], [[3]], [[4]], [[5]], [[6]], [[7]]]
array44 shape: (8, 1, 1)
array4:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array4 shape: (8, 1)
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


In [77]:
#볼게요. 
## 3차원 array를 1차원으로 변환
array1 = array3.reshape(-1,) #1차원은 열만 있어요. 어차피 행만있죠? 
# 근데 행은 모르죠?  그러면 가변 -1 넣어주지요. 
#  array3.reshape(-1,)  
#array1 = array3.reshape(-1) ## 위 코드와 같음
print(array1)
print(array1.shape)

[0 1 2 3 4 5 6 7]
(8,)


### 넘파이 ndarray의 데이터 세트 선택하기 - indexing

- 단일 인덱싱. 

In [79]:
## 1차원 ndarray 생성 : 1~9
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
## 단지 대괄호가있어서 list 가 아니다.
## 기본적으로 range 가 리턴 하는것은 array 이다!!!! 


array1: [1 2 3 4 5 6 7 8 9]


In [80]:
## index : 0 부터 시작
## array1[2] : 3번째 index 위치의 데이터 값 의미
value = array1[2]
print('value:',value)
print(type(value))
## <class 'numpy.int32'> 
## 넘파이에서 쓰이는 int32 라는 클래스 타입입니다~ 


value: 3
<class 'numpy.int32'>


In [82]:
print('맨 뒤의 값:', array1[-1])
print('맨 뒤에서 두번째 값:', array1[-2])

맨 뒤의 값: 9
맨 뒤에서 두번째 값: 8


In [83]:
## 요소 변경, 주소에 접근하고서,  값을 할당 해버린다ㅡ.
array1[0] = 9
array1[-1] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [85]:
# 개념 인덱싱은 - 결국 하나의 값에만 접근하는 것이다. 
# 2차원일때의  접근 방법!! 
array1 = np.arange(start=1, stop=10)
array2 = array1.reshape(-1, 3)  
print(array2)
print('shape >>', array2.shape)

print('(row=0, col=0) index 값:', array2[0, 0])
print('(row=0, col=1) index 값:', array2[0, 1])
print('(row=1, col=0) index 값:', array2[1, 0])
print('(row=2, col=2) index 값:', array2[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape >> (3, 3)
(row=0, col=0) index 값: 1
(row=0, col=1) index 값: 2
(row=1, col=0) index 값: 4
(row=2, col=2) index 값: 9


---
* 슬라이싱 인덱싱

In [86]:
array = np.arange(start=1, stop=10)
print('array:', array)
## 슬라이싱 - 시작 ~ 끝 범위주고 추출하기
array3 = array[0:3]
print('array3:', array3)
print(type(array3))
print('shape >>', array3.shape)

array: [1 2 3 4 5 6 7 8 9]
array3: [1 2 3]
<class 'numpy.ndarray'>
shape >> (3,)


In [ ]:
array1 = np.arange(start=1, stop=10)

## 인덱스 0~2의 값 추출
array4 = array1[0:3]
print(array4)

## 인덱스 3부터 마지막까지 추출
array5 = array1[3:]
print(array5)

## 전체 값 추출  시작 끝을 다 안주면 전체를 깊게 뜬다. 
array6 = array1[:]# copy()와 같은 효과 
print(array6)

In [91]:
# 2차원배열의 슬라이싱 ~  범위로 추출 

array1 = np.arange(start=1, stop=10)
array2 = array1.reshape(3,3)
print('array2:\n',array2)

print('array2[0:2, 0:2] \n', array2[0:2, 0:2])# 2차원적 슬라이싱 
print('array2[1:3, 0:3] \n', array2[1:3, 0:3])
print('array2[1:3, :] 모든열 \n', array2[1:3, :])
print('array2[:, :] \n', array2[:, :])
print('array2[:2, 1:] \n', array2[:2, 1:])
print('array2[:2, 0] \n', array2[:2, 0])
#행은 슬라이싱했고 ,열은 인덱싱 한 케이스 
# 나오는 결과가 1차원이 되버린다. (  열을 하나로 했기 떄문에!) 

array2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2[1:3, :] 모든열 
 [[4 5 6]
 [7 8 9]]
array2[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2[:2, 1:] 
 [[2 3]
 [5 6]]
array2[:2, 0] 
 [1 4]


In [95]:
# 인덱싱을 하면, 2차원인데,  인덱싱을 하나만 썼다>??  행이다! 
print(array2[0,:])# print(array2[ 0 ]) # 와 같다!! 
print(array2[1])
print('array2[0] shape:', array2[0].shape)
print('array2[1] shape:', array2[1].shape )

[1 2 3]
[4 5 6]
array2[0] shape: (3,)
array2[1] shape: (3,)


---
* 팬시 인덱싱

In [99]:
array1 = np.arange(start=1, stop=10)
array2 = array1.reshape(-1, 3)
print(array2)

array3 = array2[[0, 2], 2]
print('array2[[0, 2], 2] => ', array3.tolist())

array4 = array2[[0, 2], 0:2] 
## 펜시인덱싱이다 , 직접 열거한 열에 대해서만 가져온다.
# 그냥 인덱싱은 하나만 추출 할때 ( 차원 감소 효과) 쓴다. 
print('array2[[0, 2], 0:2] 인덱싱이긴한데, 여러개라서 2차원 => \n ', array4.tolist())

array5 = array2[[0, 2]]
print('array2[[0, 2]] => ', array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2[[0, 2], 2] =>  [3, 9]
array2[[0, 2], 0:2] 인덱싱이긴한데, 여러개라서 2차원 => 
  [[1, 2], [7, 8]]
array2[[0, 2]] =>  [[1, 2, 3], [7, 8, 9]]


---
* 불린 인덱싱

In [100]:
# 조건을 달아주어서 추출하기 
#팬시 - 불연속적 여러값
array1 = np.arange(start=1, stop=10)
print(array1)

# [ ] 안에 조건 입력
array3 = array1[array1 > 5]
print('array1 > 5 불린 인덱싱 결과 값 :', array3)

[1 2 3 4 5 6 7 8 9]
array1 > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [ ]:
array1 > 5

In [ ]:
val = array1 > 5
print(val)
print(type(val))
print(val.shape)

In [ ]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

### 행렬의 정렬 – sort( )와 argsort( )

* 행렬 정렬

In [ ]:
org_array = np.array([ 3, 1, 9, 5]) 
print('정렬 전 - org_array :', org_array)

## 정렬 : np.sort()
sort_array = np.sort(org_array)
print('\n<< np.sort() >>')
print('정렬 후 - sort_array :', sort_array) ## 복사본
print('정렬 후 - org_array :', org_array)    ## 원본 그대로

## 정렬 : ndarray.sort()
sort_array2 = org_array.sort()
print('\n<< ndarray.sort() >>')
print('정렬 후 - sort_array2 :', sort_array2) ## None (반환값 없음)
print('정렬 후 - org_array :', org_array)     ## 원본 적용

In [ ]:
#  시작 생략 끝 생략    - 1  << 역순으로 뽑아와줘 
sort_array_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array_desc) 

In [101]:
array2 = np.array([[8, 12], 
                   [9, 1 ]])
## sort 는 혁시 함수니깐. 복사본 만드는데,   axis - 행기준  , 열기준! 
sort_array2_axis0 = np.sort(array2, axis=0)
# 행바이 행을 비교해서 정렬 한뒤 전체보여주기 
print('로우(행) 방향으로 정렬:\n', sort_array2_axis0)

sort_array2_axis1 = np.sort(array2, axis=1)
print('컬럼(열) 방향으로 정렬:\n', sort_array2_axis1)
# 컬럼바이 컬럼을 비교해서 보여주기 

로우(행) 방향으로 정렬:
 [[ 8  1]
 [ 9 12]]
컬럼(열) 방향으로 정렬:
 [[ 8 12]
 [ 1  9]]


---
* 정렬 행렬의 인덱스 반환 argsort


In [104]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_index = np.argsort(org_array)
print(type(sort_index))
print('sort_index :', sort_index) ## 원본 인덱스 반환
# 정렬을 일단 해서 , 1 3 5 9  
# 1,3,5 , 9 ,의 기존 인덱스값을 보여줌


<class 'numpy.ndarray'>
sort_index : [1 0 3 2]


In [102]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_index_desc = np.argsort(org_array)[::-1]
print('sort_index_desc :', sort_index_desc)

sort_index_desc : [2 3 0 1]


In [106]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_index_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_index_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_index_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [107]:
sort_index_asc

array([0, 2, 4, 1, 3], dtype=int64)

In [110]:
name_array

array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'], dtype='<U6')

In [113]:
# 복수개 이상을 데려오고싶다? 
name_array[[0,2,1]]

array(['John', 'Sarah', 'Mike'], dtype='<U6')

In [114]:
# name_array 내부에 
#  np.argsort(score_array) 을 넣어서 불러내버리면
name_array[np.argsort(score_array)]
#  소팅 결과 + 이름만 보여주기가 된다! 

array(['John', 'Sarah', 'Samuel', 'Mike', 'Kate'], dtype='<U6')

### 선형대수 연산 – 행렬 내적과 전치 행렬 구하기

* 행렬 내적

In [105]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


* 전치 행렬

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

In [ ]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat) ## shape : (3, 2) -> (2, 3)