** numpy와 array 차이
## 요소 타입
- 리스트 :  숫자형, 문자열 등 모든 자료 타입을 가질 수 있다 (여러 자료형 허용)
- 어레이 : 숫자형과 문자열이 혼합되면 모두 문자열로 변환 (한 가지 자료형만 허용)

In [2]:
import numpy as np
lt = [1, 3, 'a', 'b']
ar = np.array([1, 3, 'a', 'b'])

print(lt)
print(ar)

[1, 3, 'a', 'b']
['1' '3' 'a' 'b']


## 2차원 이상일 경우, 원소 개수
- 리스트 : 원소 개수가 달라도 됨
- 어레이 : 원소 개수가 모두 같아야 함

In [8]:
lt = [[1], [3, 5], [7, 9, 10]]
ar = np.array([[1], [3, 5], [7, 9, 10]]) ## Warning

## Warning 발생 안되게 하려면...
#ar = np.array([[1], [3, 5], [7, 9, 10]], dtype=object)
ar = np.array([[1, 3], [3, 5], [7, 9]])

print(lt)
print(ar)

[[1], [3, 5], [7, 9, 10]]
[[1 3]
 [3 5]
 [7 9]]


C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_6828\1507619900.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar = np.array([[1], [3, 5], [7, 9, 10]]) ## Warning


## 연산
- 리스트 : 리스트 간 + 연산은 concatenate 수행, -,*,/ 연산 불가능
- 어레이 : +, -, *, / 연산 모두 가능

In [ ]:
#리스트를 가지고 하는 연산 , 리스트 전후순서대로 합쳐 이어주기 >
lt_one = [1, 3, 5]
lt_two = [2, 4, 6]

print(lt_one + lt_two)# concat
#print(lt_one - lt_two) ## Error
print(lt_one * 3) # iterate 

In [15]:
## ARRAY 는 좀더 다양한 일들을 할수있다!! 

ar_one = np.array([1, 3, 5])
ar_two = np.array([2, 4, 6])
print(ar_one + ar_two)
print(ar_one - ar_two)
print(ar_one * ar_two)
print(ar_one / ar_two)

print(ar_one + 2)
print(ar_one * 2)
ar_one * 2

[1, 3, 5, 2, 4, 6]
[1, 3, 5, 1, 3, 5, 1, 3, 5]
[ 3  7 11]
[-1 -1 -1]
[ 2 12 30]
[0.5        0.75       0.83333333]
[3 5 7]
[ 2  6 10]


array([ 2,  6, 10])

## 연산 속도 
- 1970년 1월 1일 0시 0분 0초 이후 경과한 시간을 초단위로 반환
- 정수부는 초단위이고, 소수부는 마이크로(micro) 초단위
- 마이크로초(microsecond, μs)또는 마이크로세컨드 : 백만 분의 1초

In [22]:
import time 

# 리스트 연산 속도
lt = list(range(10 ** 8)) ## 10 ** 8 : 10의 8제곱

start = time.time()
for i in range(10 ** 8):
    lt[i] *= 2
end = time.time()
print(end - start)

17.97659158706665


In [21]:
# 어레이 연산 속도
ar = np.array(range(10 ** 8))

start = time.time()
ar = ar * 2
end = time.time()
print(end - start)

0.1676464080810547
